sudo: false
script:
  - npm install
env:
  - VALIDATORS=tv4
  - VALIDATORS=zschema
matrix:
  allow_failures:
    - env: VALIDATORS=tv4
install:
  - rm -rf ~/.nvm
  - curl -L https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sh
  - source ~/.nvm/nvm.sh
  - nvm install 6.1
  - nvm use 6.1
script:
  - npm install
  - node node_modules/mdv/mdv versions/3.*.md
