language: scala
scala:
   - 2.10.4
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - npm install
  - mocha
env:
  - VALIDATORS=tv4
  - VALIDATORS=zschema
matrix:
  allow_failrues:
    -env: VALIDATORS=tv4
