theme: jekyll-theme-dinky
title: OpenAPI Initiative Registry - DRAFT CONTENT
description: Extensible data value repository
show_downloads: true
collections_dir: /registries
collections:
  posts:
    hidden: true
  object:
    slug: object
    name: Object Registry
    hidden: true
  format:
    slug: format
    name: Format Registry
    output: true
    permalink: /registry/:collection/:title
  extension:
    slug: extension
    name: Specification Extension Registry
    output: true
    permalink: /registry/:collection/:title
  draft-feature:
    slug: draft-feature
    name: Draft Features Registry
    output: true
    permalink: /registry/:collection/:title
  alternative-schema:
    slug: alternative-schema
    name: Alternative Schema Type Registry
    output: true
    permalink: /registry/:collection/:title
